[package]
name = "clouisle-net"
version.workspace = true
edition.workspace = true

[dependencies]
clouisle-core = { path = "../clouisle-core" }
libc.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
uuid.workspace = true
futures.workspace = true
bytes.workspace = true
hickory-resolver = { version = "0.26", features = ["tokio"] }
hickory-proto = "0.26"
socket2 = { version = "0.5", features = ["all"] }
sha2.workspace = true
hex.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.29", features = ["fs", "sched", "net", "socket", "mount"] }
rtnetlink = "0.14"

[features]