[package]
name = "clouisle-vmm"
version.workspace = true
edition.workspace = true

[dependencies]
clouisle-core = { path = "../clouisle-core" }
clouisle-proto = { path = "../clouisle-proto" }
clouisle-images = { path = "../clouisle-images" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
uuid.workspace = true
hyper.workspace = true
hyperlocal = { workspace = true, features = ["client"] }
hyper-util = "0.1"
http-body-util = "0.1"
futures.workspace = true
bytes.workspace = true
bollard = { version = "0.18", default-features = false, features = ["http", "pipe"] }
tokio-stream = "0.1"
tar = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.29", features = ["fs", "process", "signal"] }
sha2 = { workspace = true }
hex = { workspace = true }

