[package]
name = "clouisled"
version.workspace = true
edition.workspace = true

[dependencies]
clouisle-core = { path = "../clouisle-core" }
clouisle-vmm = { path = "../clouisle-vmm" }
clouisle-store = { path = "../clouisle-store" }
clouisle-scheduler = { path = "../clouisle-scheduler" }
clouisle-proto = { path = "../clouisle-proto" }
clouisle-net = { path = "../clouisle-net" }
clouisle-pool = { path = "../clouisle-pool" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
chrono.workspace = true
clap.workspace = true
tonic = "0.12"
prost = "0.13"
tokio-stream = "0.1"
bytes.workspace = true
futures.workspace = true
reqwest.workspace = true

[build-dependencies]
tonic-build = "0.12"

